logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:postgresql://props-postgres:8088/propsdb
spring.datasource.url=jdbc:postgresql://localhost:8088/propsdb

spring.datasource.username=dbuser
spring.datasource.password=12345
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
