
DROP TABLE IF EXISTS FORMS CASCADE;
DROP TABLE IF EXISTS DIPLOMAS CASCADE;
DROP TABLE IF EXISTS GAMES CASCADE;
DROP TABLE IF EXISTS COMPOSITIONS CASCADE;
DROP TABLE IF EXISTS RULES CASCADE;

create table forms (
id varchar primary key,
title varchar unique,
quantity integer default 0
);
